import sqlite3
from pathlib import Path

path = Path(__file__).parent.parent / "tasks"
conn = sqlite3.connect(path / "sqlite.db")


# Start: generated by gemini
# Reason: looks better than anything I could create in 10x the time (AI good at text formatting)
def peak() -> str:
    output = []
    try:
        cursor = conn.cursor()

        # 1. Get all table names
        cursor.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%';"
        )
        tables = cursor.fetchall()

        if not tables:
            return "⚠️ Status: Database is EMPTY (No tables found)."

        output.append(f"✅ Database initialized with {len(tables)} tables:")
        output.append("-" * 30)

        for (table_name,) in tables:
            # 2. Get the row count
            cursor.execute(f"SELECT COUNT(*) FROM {table_name}")
            count = cursor.fetchone()[0]

            status = "🌱 Seeded" if count > 0 else "⚪ Empty"
            output.append(f"{status:<10} | {table_name:<15} | Rows: {count}")

        return "\n".join(output)

    except sqlite3.ProgrammingError:
        return "❌ Error: The database connection is closed."
    except Exception as e:
        return f"❌ Unexpected Error: {e}"


# End: generated by gemini


def runScript(fileName):
    cur = conn.cursor()

    sql_file = path / fileName
    sql_script = sql_file.read_text()

    cur.executescript(sql_script)

    conn.commit()
    cur.close()
