import os
from typing import Dict, Callable, Any

MenuActions = Dict[str, Callable[[], Any]]


class Page:
    def __init__(self, link: MenuActions, content: str):
        self.link = link
        self.content = content
        self.prev: "Page" | None = None


class History:
    def __init__(self):
        self.cur: Page | None = None

    def append(self, link: MenuActions, content: str):
        new_page = Page(link, content)
        if self.cur is not None:
            new_page.prev = self.cur
        self.cur = new_page
        state.setFrame(content)

    def goBack(self):
        if self.cur and self.cur.prev:
            self.cur = self.cur.prev
            state.setFrame(self.cur.content)
            self.run()
        return False

    def run(self):
        while self.cur:
            if not state.render(self.cur.link):
                break


class State:
    def __init__(self):
        self.frame = ""

    def render(self, actions: MenuActions):
        rows, _ = os.get_terminal_size()
        # Start: generated by gemini (Clear screen and move to top)
        print("\033[H\033[J", end="")
        # End: generated by gemini

        keys = list(actions.keys())
        for index, key in enumerate(keys, start=1):
            print(index, " : ", key)

        print('Go Back: "b", "back", "<", "-1", "cd .."')

        print("\n\n\n", self.frame, "\n")

        # Start: generated by gemini (Move cursor to bottom of screen)
        print(f"\033[{rows};1H", end="")
        # End: generated by gemini

        choise = input("Selection > ").strip().lower()

        if choise in ["b", "back", "<", "-1", "cd .."]:
            history.goBack()

        if not choise.isdigit():
            return True

        choise = int(choise)

        if len(keys) <= choise < 0:
            return True

        key = keys[choise - 1]

        actions[key]()
        self.frame = ""
        return True

    def setFrame(self, content):
        self.frame = content


state = State()
history = History()
