-- Start: Test data generated by gemini
INSERT INTO SignUps (user_id, session_id) VALUES 
-- Johnny's Training History (User 14)
(14, 1), (14, 3), (14, 10), (14, 11), (14, 13),
-- Thomas-Andre's History (User 13) - Often training with Johnny
(13, 1), (13, 5), (13, 11), (13, 13),
-- Eirin (User 1) - High attendance for Top Performer query
(1, 1), (1, 2), (1, 4), (1, 6), (1, 8), (1, 10), (1, 12),
-- Nora (User 4) - High attendance (tied with Eirin)
(4, 1), (4, 3), (4, 5), (4, 7), (4, 9), (4, 11), 
-- Sindre (User 7) - Casual attendance
(7, 2), (7, 4), (7, 10), (7, 12),
-- Amalie (User 9) - Joint training with Johnny in Session 8
(9, 8), (9, 9), (9, 10),
-- Ramona (User 10)
(10, 3), (10, 4), (10, 11),
-- Siri (User 11)
(11, 12), (11, 13), (11, 5),
-- Ada (User 12)
(12, 1), (12, 2), (12, 13),
-- Hakon (User 5)
(5, 6), (5, 7), (5, 8),
-- Kaja (User 8)
(8, 1), (8, 9), (8, 11);
-- End: test data generated by gemini
