import sqlite3
from pathlib import Path

path = Path(__file__).parent.parent / "tasks"
conn = sqlite3.connect(path / "sqlite.db")


# Start: generated by gemini
# Reason: looks better than anything I could create in 10x the time (AI good at text formatting)
def peak() -> str:
    output = []
    try:
        cursor = conn.cursor()

        # 1. Get all table names
        cursor.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%';"
        )
        tables = cursor.fetchall()

        if not tables:
            return "⚠️ Status: Database is EMPTY (No tables found)."

        output.append(f"✅ Database initialized with {len(tables)} tables:")
        output.append("-" * 30)

        for (table_name,) in tables:
            # 2. Get the row count
            cursor.execute(f"SELECT COUNT(*) FROM {table_name}")
            count = cursor.fetchone()[0]

            status = "🌱 Seeded" if count > 0 else "⚪ Empty"
            output.append(f"{status:<10} | {table_name:<15} | Rows: {count}")

        return "\n".join(output)

    except sqlite3.ProgrammingError:
        return "❌ Error: The database connection is closed."
    except Exception as e:
        return f"❌ Unexpected Error: {e}"


# End: generated by gemini


# Start: reworked by chatgpt for better error messages
def runScript(fileName):
    cur = conn.cursor()

    sql_file = path / fileName
    sql_script = sql_file.read_text()

    statements = sql_script.split(";")

    for i, stmt in enumerate(statements, 1):
        stmt = stmt.strip()
        if not stmt:
            continue

        try:
            cur.execute(stmt)
        except Exception as e:
            print(f"\nSQL error in {fileName}")
            print(f"Statement #{i}:\n")
            print(stmt)
            print("\nError:", e)
            raise

    conn.commit()
    cur.close()


# End reworked by chatgpt


def dropTables():
    cur = conn.cursor()

    cur.execute("PRAGMA foreign_keys = OFF")

    # Generated by chatgpt to save time
    tables = [
        "Reservations",
        "TeamMembers",
        "Teams",
        "Waitlist",
        "PenaltyDots",
        "SignUps",
        "Sessions",
        "SessionTypes",
        "Treadmills",
        "Bicycles",
        "Manufacturers",
        "Halls",
        "StaffHours",
        "Staff",
        "Users",
        "OpeningHours",
        "CenterFacilities",
        "Facilities",
        "Centers",
        "Locations",
    ]
    # End generated by chatgpt

    for table in tables:
        cur.execute(f"DROP TABLE IF EXISTS {table};")

    conn.commit()
